### PR TITLE
Attempt to rewrite BUNDLE with improved terminology

### PR DESCRIPTION
**Pull request by taylor-b**
I've seen some confusion around the terms "unique address"/"shared address", and concern that when defined around these terms, the specification isn't extensible to protocols like ICE, where a transport isn't identified by an address (in the case of ICE, it's identified with ufrags).

So, I'm attempting to replace the current set of terminology with one that's easier to understand, and more generalizable. The major things done in this PR are:

* Got rid of "unique address"/"shared address" concept. Instead, "bundled"
  vs "not bundled" and "offers fallback" vs "doesn't offer fallback" are the
  central concepts discussed.
* Using "media transport" concept from RFC7656, which is more general
  than just an IP/port combination. This fixes the concern with ICE as
  mentioned above.
* Got rid of "offerer BUNDLE-tag". Instead using "BUNDLE-section", to
  mean "the m= section whose attributes are actually used for the BUNDLE
  group".
* Replaced "associated with..." with more specific phrases describing the
  relationships between objects, to reduce ambiguity.
* Deleted some sections that in the end were redundant, either
  because the same rules are somewhere else in the document or they're
  in sdp-mux-attributes.
* Discovered some issues I didn't notice before and documented them.
  Can raise to the mailing list if there's agreement that they're issues.

### CODE REVIEW

**Comment by taylor-b** [comment]
@cdh4u, could you take a look when you have time? I'm trying to resolve some of the ambiguity that I've seen brought up on the mailing list, and that I've experienced as an implementer.

Which of these changes do you agree with? And where would you like to go from here? Thanks!

**Comment by cdh4u** [comment]
Thanks for the pull request! I see that there are quite many changes, so it will take a while before I have a time slot to sit down and go through everything. But, I will do it :)

**Comment by taylor-b** [comment]
Thanks; if it will make it easier to review, I can split it into separate PRs (for deleted/moved sections, major terminology changes, and pure editorial changes, for example).

**Comment by cdh4u** [comment]
I think that would be useful. Regarding pure editorial changes, I think the chairs have previously indicated that that train has left, and we shouldn't do them unless something is really misleading or difficult for understand. For example, I see no reason to change "m- line" to "m- section".

Also, you seem to have added a number of "ISSUES". Also, unless multiple issues are identical, I'd suggest to create separate PRs for each of them. Otherwise it will be very messy when we discuss them. Also, at this point I would not want to add the ISSUE text in to the draft. Please provide it in the PR description instead.

**Comment by taylor-b** [comment]
Alright; I documented the issues with github, and created a separate PR that attempts to capture the independent editorial changes: https://github.com/taylor-b/draft-sdp-bundle/pull/1

Also: I actually do feel a bit strongly about using the terms '"m=" line' and '"m=" section' consistently. Other IETF documents I've seen only use '"m=" line' to refer to the line itself, as will JSEP (see: https://github.com/rtcweb-wg/jsep/pull/487). And 'attribute contained in an "m=" section" is more readable to me than 'attribute associated with an "m=" line'.

**Comment by cdh4u** [comment]
Many of the suggested changes were done in other PRs.

**Pull request closed without merging**
