### PR TITLE
RTP mapping text from draft-jsep-19

### PR DESCRIPTION
**Pull request by cdh4u**
Moving text from Appendix B of draft-jsep-19 into draft-bundle.

### CODE REVIEW

**Comment by cdh4u** [comment]
Absolutely.

**Comment by fluffy** [comment]
I would like to see us adopting this text - I think it is much better than the current text. There has been a lot of discussion in github to get to this point.

**Comment by cdh4u** [comment]
The "impact of BYE on ssrc table" issue may still impact the text, right?

**Comment by fluffy** [comment]
Yes, we definitely need to resolve https://github.com/rtcweb-wg/jsep/issues/621 and get the update into the text here.

**Pull request merged**
